[build]
  command = "npm ci && npm run build:netlify"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV"

[[plugins]]
  package = "@netlify/plugin-nextjs"
